# Generated by Django 5.0.2 on 2024-02-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='slug',
        ),
    ]
